### ISSUE TITLE
Dune build error both in docker and local with "TYPE_VAR" not matched

### ISSUE THREAD

**Issue by cyruliu** [hiroshi-unno/coar#1]
Hi,

I was trying to build both from source and docker image, facing the same error as following, I tried on both `Z3 version 4.12.4 - 64 bit`, and `Z3 version 4.8.8 - 64 bit`:

> [builder 7/7] RUN eval $(opam env) && dune build main.exe:                                                                                                  
5.736 Warning: one state end-of-stream conflict was arbitrarily resolved.                                                                                      
10.50 File "lib/ast/rtypeParser.mly", line 113, characters 0-5:                                                                                                
10.50 Warning: the precedence level assigned to AMP is never useful.                                                                                           
10.50 File "lib/ast/rtypeParser.mly", line 109, characters 0-5:                                                                                                
10.50 Warning: the precedence level assigned to COMMA is never useful.                                                                                         
10.50 File "lib/ast/rtypeParser.mly", line 114, characters 0-6:
10.50 Warning: the precedence level assigned to EXC is never useful.
10.50 File "lib/ast/rtypeParser.mly", line 115, characters 0-9:
10.50 Warning: the precedence level assigned to EXISTS is never useful.
10.50 File "lib/ast/rtypeParser.mly", line 115, characters 0-9:
10.50 Warning: the precedence level assigned to FORALL is never useful.
10.50 File "lib/ast/rtypeParser.mly", line 106, characters 0-5:
10.50 Warning: the precedence level assigned to prec_tyapp is never useful.
10.50 File "lib/ast/rtypeParser.mly", line 104, characters 0-6:
10.50 Warning: the precedence level assigned to prec_tyarrow is never useful.
10.50 File "lib/ast/rtypeParser.mly", line 105, characters 0-9:
10.50 Warning: the precedence level assigned to prec_typair is never useful.
10.50 File "lib/ast/rtypeParser.mly", line 362, characters 23-33:
10.50 Warning: this %prec declaration is never useful.
10.50 File "lib/ast/rtypeParser.mly", line 369, characters 44-54:
10.50 Warning: this %prec declaration is never useful.
10.50 File "lib/ast/rtypeParser.mly", line 373, characters 31-43:
10.50 Warning: this %prec declaration is never useful.
10.50 File "lib/ast/rtypeParser.mly", line 376, characters 57-69:
10.50 Warning: this %prec declaration is never useful.
10.50 File "lib/ast/rtypeParser.mly", line 379, characters 22-33:
10.50 Warning: this %prec declaration is never useful.
10.50 Warning: 24 states have shift/reduce conflicts.
10.50 Warning: 2 states have reduce/reduce conflicts.
10.50 Warning: 50 shift/reduce conflicts were arbitrarily resolved.
10.50 Warning: 24 reduce/reduce conflicts were arbitrarily resolved.
10.50 Warning: 117 end-of-stream conflicts were arbitrarily resolved.
10.50 File "lib/ast/rtypeParser.mly", line 473, characters 4-13:
10.50 Warning: production assertions -> assertion is never reduced.
10.50 File "lib/ast/rtypeParser.mly", line 466, characters 4-8:
10.50 Warning: production constraints -> prop is never reduced.
10.50 File "lib/ast/rtypeParser.mly", line 507, characters 4-12:
10.50 Warning: production opt_problems -> opt_pair is never reduced.
10.50 File "lib/ast/rtypeParser.mly", line 443, characters 4-15:
10.50 Warning: production val_ty_env -> val_ty_bind is never reduced.
10.50 File "lib/ast/rtypeParser.mly", line 390, characters 4-26:
10.50 Warning: production val_tys_ast -> val_ty AST val_tys_ast is never reduced.
10.50 Warning: in total, 5 productions are never reduced.
12.07 File "lib/Z3Smt/z3interface.ml", lines 116-167, characters 2-80:
12.07 116 | ..match Z3.Sort.get_sort_kind s with
12.07 117 |   | Z3enums.UNINTERPRETED_SORT ->
12.07 118 |     let name = Z3.Symbol.get_string @@ Z3.Sort.get_name s in
12.07 119 |     if String.is_prefix ~prefix:unint_svar_prefix name then
12.07 120 |       let svar = String.sub name ~pos:(String.length unint_svar_prefix)
12.07 ...
12.07 164 |   | Z3enums.RE_SORT -> T_regex.SRegEx
12.07 165 |   | Z3enums.CHAR_SORT -> failwith "CHAR_SORT not supported"
12.07 166 |   | Z3enums.UNKNOWN_SORT ->
12.07 167 |     failwith @@ "[z3:sort_of] UNKNOWN_SORT not supported:" ^ Z3.Sort.to_string s
12.07 Error (warning 8 [partial-match]): this pattern-matching is not exhaustive.
12.07 Here is an example of a case that is not matched:
12.07 TYPE_VAR
------
It got compiled after adding this case match `TYPE_VAR -> failwith …`  to the file `lib/Z3Smt/z3interface.ml`.

Best,
Cyrus

**Comment by hiroshi-unno** [comment]
Thank you.  The commit f677d82b56c7c8dcee3cd2d193ddb23028537b56 fixes this.
